# generate_comic.py

from diffusers import StableDiffusionXLPipeline
import torch
from datetime import datetime
import os
import random
from PIL import Image, ImageDraw, ImageFont

# (All your comic generation code stays here — mood selection, image generation, 2x2 layout, captions, etc.)
# Assume everything you pasted before is still present

# Save mood label
with open("images/mood.txt", "w") as f:
    f.write(daily_mood)
print(f"📄 Mood saved: {daily_mood}")

# ✅ Generate latest.html from template
try:
    template_path = "latest_template.html"  # Template file with {{ mood }} etc.
    with open(template_path, "r") as f:
        template = f.read()

    comic_title = f"Super Smidge – {daily_mood} Edition"
    date_str = datetime.utcnow().strftime("%B %d, %Y")

    filled = (
        template.replace("{{ comic_title }}", comic_title)
                .replace("{{ mood }}", daily_mood)
                .replace("{{ date }}", date_str)
    )

    with open("latest.html", "w") as f:
        f.write(filled)

    print("✅ latest.html successfully generated")

except Exception as e:
    print("❌ Failed to generate latest.html:", e)
