name: Generate Super Smidge Comic Daily

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC
  workflow_dispatch:

jobs:
  generate-comic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install diffusers torch accelerate transformers Pillow

      - name: Run comic generator
        run: python generate_comic.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Bootstrap latest.html if missing
        run: |
          if [ ! -f latest.html ]; then
            cp latest_template.html latest.html
            sed -i 's/{{ comic_title }}/Super Smidge – Launch Edition/' latest.html
            sed -i 's/{{ mood }}/Joyful/' latest.html
            sed -i "s/{{ date }}/$(date +'%B %d, %Y')/" latest.html
          fi

      - name: Commit and push updated comic + HTML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add .  # ✅ Stage everything early to avoid unstaged changes error
          git pull --rebase origin main
          git commit -m "🌟 Auto-update: Comic and latest.html" || echo "🟡 Nothing to commit"
          git push

      - name: Add link to comic page
        run: |
          sed -i '/<\/body>/i <p><a href="latest.html">📖 View Full Comic with Mood and Story<\/a><\/p>' index.html
