name: Daily Mood Comic

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install diffusers transformers accelerate torch pillow

      - name: 🎨 Generate daily mood comic
        run: python generate_comic.py

      - name: 📤 Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/
          git commit -m "🤖 Daily mood comic update" || echo "No changes to commit"
          git push
