name: Generate Superdog Image Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install diffusers torch accelerate transformers

      - name: Run image generator
        run: python ./generate_image.py
        env:
          HF_TOKEN: ${{ secrets.GH_PAT  }}

      - name: Commit and push new image
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/Atlas5033/superdog-gallery.git
          git add images/
          git commit -m "New image for hour" || echo "🟡 Nothing to commit"
          git push origin HEAD:main
        continue-on-error: true
